-- ********************************************************
-- **               Memoria - esES Local                 **
-- **           <http://nanaki.affenfelsen.de>           **
-- ********************************************************
--
-- This localization is written by:
--  <nobody>
--

-- Check for addon table
if (not Memoria) then Memoria = {}; end
if GetLocale() ~= "esES" then return end

-- Localization
--[[Translation missing --]]
--[[ Memoria.L["arena endings"] = "arena endings"--]] 
--[[Translation missing --]]
--[[ Memoria.L["battleground endings"] = "battleground endings"--]] 
--[[Translation missing --]]
--[[ Memoria.L["bosskills"] = "boss kills"--]] 
--[[Translation missing --]]
--[[ Memoria.L["challenge instance endings"] = "mythic+ instance endings"--]] 
--[[Translation missing --]]
--[[ Memoria.L["days"] = "days"--]] 
--[[Translation missing --]]
--[[ Memoria.L["exalted only"] = "exalted only"--]] 
--[[Translation missing --]]
--[[ Memoria.L["hours"] = "hours"--]] 
--[[Translation missing --]]
--[[ Memoria.L["level up"] = "level up"--]] 
--[[Translation missing --]]
--[[ Memoria.L["minutes"] = "minutes"--]] 
--[[Translation missing --]]
--[[ Memoria.L["new achievement"] = "new achievement"--]] 
--[[Translation missing --]]
--[[ Memoria.L["new reputation level"] = "new reputation level"--]] 
--[[Translation missing --]]
--[[ Memoria.L["only after first kill"] = "only once per difficulty"--]] 
--[[Translation missing --]]
--[[ Memoria.L["resize chat window"] = "Resize chat window for played message"--]] 
--[[Translation missing --]]
--[[ Memoria.L["seconds"] = "seconds"--]] 
--[[Translation missing --]]
--[[ Memoria.L["show played"] = "show /played in chat"--]] 
--[[Translation missing --]]
--[[ Memoria.L["Take screenshot on"] = "Take screenshot on"--]] 
--[[Translation missing --]]
--[[ Memoria.L["time played"] = "Time played at level"--]] 
--[[Translation missing --]]
--[[ Memoria.L["wins only"] = "wins only"--]] 

